name: Daily Memes in README

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 14 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-meme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Git
        run: |
          git config --local user.email "tima.privalov2008@gmail.com"
          git config --local user.name "timplif"

      - name: Run meme script
        run: python3 add_meme.py

      - name: Commit and Push
        run: |
          git add README.md
          git commit -m "😂 Added meme"
          git push
